spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: stocksappsmtpmohsun@gmail.com
    password: # enter the password here
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
