spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: mohsun
    password: 123
    url: jdbc:mariadb://localhost:3306/stocks_app_db
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: stocksappsmtpmohsun@gmail.com
    password: # enter the password here
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml